[package]
name = "bifrost"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]

[lib]
name = "bifrost"

[[test]]
name = "tests"

[dependencies]
bincode = "*"
byteorder = "1"
env_logger = "0.4"
log = "0.3.1"
slab = "0.3.0"
serde = "*"
serde_derive = "*"
bifrost_plugins = { path = "src/plugins" }
bifrost_hasher = { path = "src/hasher" }
rand = "0.3"

futures-cpupool = "0.1"
futures-await = "0.1"

lazy_static = "0.2"
threadpool = "1.0"
num_cpus = "1.0"
parking_lot = {version = "0.6", features = ["nightly"]}
thread-id = "3.0.0"

tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-timer = "0.1"
tokio-middleware = { git = "https://github.com/tokio-rs/tokio-middleware" }

[dev-dependencies]
rayon = "1.0"