[package]
name = "bifrost"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]

[lib]
name = "bifrost"

[[test]]
name = "tests"

[dependencies]
bincode = "1"
byteorder = "1"
log = "0.4"
env_logger = "0.5"
serde = "1"
serde_derive = "1"
bifrost_plugins = { path = "src/plugins" }
bifrost_hasher = { path = "src/hasher" }
rand = "0.4"

futures = "0.2"
futures-channel = "0.2"

lazy_static = "1"
threadpool = "1"
num_cpus = "1"
parking_lot = {version = "0.5", features = ["nightly"]}

tokio = "0.1"
tokio-io = "0.1"
bytes = "0.4"

[dev-dependencies]